schedules:
- cron: "*/5 * * * *"
  displayName: Every 5 minutes
  branches:
    include:
    - main

pool:
  name: Default

steps:

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JAVA_HOME'
    jdkUserInputPath: '/Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    arguments: '--configuration $(buildConfiguration)'
    tasks: 'clean build test'
